version: '3'

networks:
  mysql-phpmyadmin:
    # use the bridge driver
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: vyv
      MYSQL_DATABASE: vv_practica
    ports:
      - "33060:3306"
    volumes:
      - ./resources:/docker-entrypoint-initdb.d
    networks:
      mysql-phpmyadmin:
        aliases:
          - mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8912:80"
    networks:
      mysql-phpmyadmin:
        aliases:
          - phpmyadmin